# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68d176670725a1d423ebfc6346109107e8afab523bda98a4a89ffa309a0109601ffd2942bfb5ea95e6f5cb3a8ab34979723d04b618f5cc27510ba84afe0f4a8

test:
  secret_key_base: f547f0947240677229dd60a7f31a4a6ed8aed942210bf97dcb61ada766e428f92c3fde27de20f79b0f76d2b9df711124384098664d4892fbc2b6da761f1ae9d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
